package congress

type State struct {
	ID   string
	Long string
}

var States = []State{
	{ID: "AK", Long: "Alaska"},
	{ID: "AL", Long: "Alabama"},
	{ID: "AR", Long: "Arkansas"},
	{ID: "AZ", Long: "Arizona"},
	{ID: "CA", Long: "California"},
	{ID: "CO", Long: "Colorado"},
	{ID: "CT", Long: "Connecticut"},
	{ID: "DC", Long: "District of Columbia"},
	{ID: "DE", Long: "Delaware"},
	{ID: "FL", Long: "Florida"},
	{ID: "GA", Long: "Georgia"},
	{ID: "HI", Long: "Hawaii"},
	{ID: "IA", Long: "Iowa"},
	{ID: "ID", Long: "Idaho"},
	{ID: "IL", Long: "Illinois"},
	{ID: "IN", Long: "Indiana"},
	{ID: "KS", Long: "Kansas"},
	{ID: "KY", Long: "Kentucky"},
	{ID: "LA", Long: "Louisiana"},
	{ID: "MA", Long: "Massachusetts"},
	{ID: "MD", Long: "Maryland"},
	{ID: "ME", Long: "Maine"},
	{ID: "MI", Long: "Michigan"},
	{ID: "MN", Long: "Minnesota"},
	{ID: "MO", Long: "Missouri"},
	{ID: "MS", Long: "Mississippi"},
	{ID: "MT", Long: "Montana"},
	{ID: "NC", Long: "North Carolina"},
	{ID: "ND", Long: "North Dakota"},
	{ID: "NE", Long: "Nebraska"},
	{ID: "NH", Long: "New Hampshire"},
	{ID: "NJ", Long: "New Jersey"},
	{ID: "NM", Long: "New Mexico"},
	{ID: "NV", Long: "Nevada"},
	{ID: "NY", Long: "New York"},
	{ID: "OH", Long: "Ohio"},
	{ID: "OK", Long: "Oklahoma"},
	{ID: "OR", Long: "Oregon"},
	{ID: "PA", Long: "Pennsylvania"},
	// {ID: "PR", Long: "Puerto Rico"},
	{ID: "RI", Long: "Rhode Island"},
	{ID: "SC", Long: "South Carolina"},
	{ID: "SD", Long: "South Dakota"},
	{ID: "TN", Long: "Tennessee"},
	{ID: "TX", Long: "Texas"},
	{ID: "UT", Long: "Utah"},
	{ID: "VA", Long: "Virginia"},
	{ID: "VT", Long: "Vermont"},
	{ID: "WA", Long: "Washington"},
	{ID: "WI", Long: "Wisconsin"},
	{ID: "WV", Long: "West Virginia"},
	{ID: "WY", Long: "Wyoming"},
}
